name: "Update Flake Packages ❄️"

on:
    workflow_dispatch: {}
    schedule:
        # Runs every Sunday at midnight
        - cron: "0 0 * * 0"

jobs:
    update-flake-packages:
        runs-on: "ubuntu-latest"
        steps:
          - name: "Checkout repository"
            uses: "https://code.forgejo.org/actions/checkout@v3"
          - name: "Install Nix"
            uses: "https://github.com/cachix/install-nix-action@v20"
          - name: "Update flake packages"
            uses: "https://github.com/poperigby/nix-update-action"
            with:
                pr-assignees: "PopeRigby"
