name: "Update Flake Packages ❄️"

on:
    workflow_dispatch: {}
    schedule:
        # Runs every Sunday at midnight
        - cron: "0 0 * * 0"

jobs:
    update-flake-packages:
        runs-on: "haddock"
        steps:
          - name: "Checkout repository"
            uses: "actions/checkout@v3"
          - name: "Install Nix"
            uses: "PopeRigby/install-nix-action@v20"
          - name: "Update flake packages"
            uses: "PopeRigby/nix-update-action@303b1ca2e34d29bf0640bd2b94df93177ef2b275"
            with:
                pr-assignees: "PopeRigby"
