name: "Update Flake Packages ❄️"

on:
    workflow_dispatch: {}
    schedule:
        # Runs Sunday at midnight
        - cron: "0 0 * * 0"

jobs:
  update-derivation:
      runs-on: "ubuntu-latest:docker"
      steps:
        - name: "Set up cache for Nix"
          uses: "actions/cache@v3"
          with:
              path: "/nix/store"
              key: "${{ runner.os }}-nix-store-${{ github.ref }}"
              restore-keys: "${{ runner.os }}-nix-store-"
        - name: "Checkout repository"
          uses: "actions/checkout@v3"
        - name: "Install Nix"
          uses: "cachix/install-nix-action@v20"
        - name: "Update flake packages"
          uses: "selfuryon/nix-update-action@v1"
          with:
              pr-assignees: "PopeRigby"
