name: "Update Flake Packages ❄️"

on:
    workflow_dispatch: {}
    schedule:
        # Runs every Sunday at midnight
        - cron: "0 0 * * 0"

jobs:
    update-flake-packages:
        runs-on: "debian-latest"
        steps:
          - name: "Checkout repository"
            uses: "actions/checkout@v3"
          - name: "Install Nix"
            uses: "PopeRigby/install-nix-action@v20"
          - name: "Update flake packages"
            uses: "PopeRigby/nix-update-action@29ce2dcf08755bf4af4390571ac53f5f7163ee36"
            with:
                pr-assignees: "PopeRigby"
